[Geral]
IdentificaMensagens=1
TransacoesAdicionaisHabilitadas=7;8;9;38;37;4178;56;57;58
EmAmbienteDeHomologacao=1
NumeroDeDiasNoLog=0
;TransacoesDesabilitadas=
;TipoComunicacaoExterna=TLSGWP
;GwpTipoProxy=http
;GwpEnderecoProxy=127.0.0.1
;TokenRegistro=1234-5678-9012-3456  # ativar em producao ou quando for fazer o teste TLS



[Sitef]
;ConfiguraEnderecoIP=tls-prod.fiservapp.com

[PinPadCompartilhado]
Porta=AUTO_USB

[CliSiTef]
HabilitaTrace=1

[CliSiTefI]
HabilitaTrace=1

[Redes]
HabilitaRede4All=1
