version: '3.8'

services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: hotel-ngrok
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - http
      - --domain=${NGROK_DOMAIN:-random}
      - backend:8000
    ports:
      - "4040:4040"
    networks:
      - hotel-network

networks:
  hotel-network:
    external: true
